// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1SNmYIaRF5xRVfWGD0yrHxXoyHXBKR0',
    appId: '1:174887027983:web:f1564dea3f31ec08376a7a',
    messagingSenderId: '174887027983',
    projectId: 'camello-family-tree',
    authDomain: 'camello-family-tree.firebaseapp.com',
    storageBucket: 'camello-family-tree.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQoLSP4gIAyda_T4iEfncIE91ztdUyNSw',
    appId: '1:174887027983:android:cb23ac471fa4499d376a7a',
    messagingSenderId: '174887027983',
    projectId: 'camello-family-tree',
    storageBucket: 'camello-family-tree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBunc5sLB3XVl4qYjvhDzDdwhy-T_c7srY',
    appId: '1:174887027983:ios:9b78fa858a44b3f9376a7a',
    messagingSenderId: '174887027983',
    projectId: 'camello-family-tree',
    storageBucket: 'camello-family-tree.firebasestorage.app',
    iosBundleId: 'com.example.camelloFamilyTree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBunc5sLB3XVl4qYjvhDzDdwhy-T_c7srY',
    appId: '1:174887027983:ios:9b78fa858a44b3f9376a7a',
    messagingSenderId: '174887027983',
    projectId: 'camello-family-tree',
    storageBucket: 'camello-family-tree.firebasestorage.app',
    iosBundleId: 'com.example.camelloFamilyTree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo1SNmYIaRF5xRVfWGD0yrHxXoyHXBKR0',
    appId: '1:174887027983:web:d84114e4da37c3e6376a7a',
    messagingSenderId: '174887027983',
    projectId: 'camello-family-tree',
    authDomain: 'camello-family-tree.firebaseapp.com',
    storageBucket: 'camello-family-tree.firebasestorage.app',
  );

}